CREATE TABLE users
(
   id UUID PRIMARY KEY,
   name VARCHAR (64) NOT NULL,
   email VARCHAR (128) UNIQUE NOT NULL,
   phone VARCHAR (16) UNIQUE NOT NULL,
   role VARCHAR (16) NOT NULL,
   created_by VARCHAR (64) NOT NULL,
   updated_by VARCHAR (64) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW (),
   updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW ()
);